export const BUS_SEARCH = "BUS_SEARCH";
export const FILTER = "FILTER";
export const SEARCH_BUTTON = "SEARCH_BUTTON";
export const BUS_DATAS = "BUS_DATAS";
export const GET_DATA = "GET_DATA";
export const BUS_LIST = "BUS_LIST";
export const GET_FILTER_DATA = "GET_FILTER_DATA";
export const SHARE_BUTTON = "SHARE_BUTTON";
export const REARRANGE_ORDER = "REARRANGE_ORDER";
export const HOME_SELECTED_DATE = "HOME_SELECTED_DATE";
export const SEAT_TYPE = "SEAT_TYPE";
export const PROFILE_DATA = "PROFILE_DATA";
export const PASSENGER_DATA = "PASSENGER_DATA";
export const FAQS = "FAQS";
export const FOOTER = "FOOTER";
export const ADS_LIST = "ADS_LIST";
export const PROMOTION_LIST = "PROMOTION_LIST";
export const CARD_DETAIL = "CARD_DETAIL";
export const TOP_ROUTE_LIST = "TOP_ROUTE_LIST";
export const PDP = "PDP";
export const SEAT_LAYOUT = "SEAT_LAYOUT";
export const OFFERS_OCCUPATION = "OFFERS_OCCUPATION";
export const DROP_POINT_LIST = "DROP_POINT_LIST";
export const GET_BOOKING_DETAILS = "GET_BOOKING_DETAILS";
export const TBS_INFO = "TBS_INFO";
export const GET_OPERATOR_LIST = "GET_OPERATOR_LIST";
export const FEED_BACK = "FEED_BACK";
export const SEND_OTP = "SEND_OTP";
export const BOOKING_DETAILS_STATUS = "BOOKING_DETAILS_STATUS";
export const GET_TICKET_TO_CANCEL = "GET_TICKET_TO_CANCEL";
export const GET_THEME_COLORS ="GET_THEME_COLORS"
export const SEND_APP_LINK ="SEND_APP_LINK"
export const MOB_ADS_LIST = "MOB_ADS_LIST"
 